// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pSmirnov2x
double pSmirnov2x(double statistic, int nx, int ny);
RcppExport SEXP _DescToolsGraphics_pSmirnov2x(SEXP statisticSEXP, SEXP nxSEXP, SEXP nySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type statistic(statisticSEXP);
    Rcpp::traits::input_parameter< int >::type nx(nxSEXP);
    Rcpp::traits::input_parameter< int >::type ny(nySEXP);
    rcpp_result_gen = Rcpp::wrap(pSmirnov2x(statistic, nx, ny));
    return rcpp_result_gen;
END_RCPP
}
// pKS2
NumericVector pKS2(NumericVector statistic, double tol);
RcppExport SEXP _DescToolsGraphics_pKS2(SEXP statisticSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type statistic(statisticSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(pKS2(statistic, tol));
    return rcpp_result_gen;
END_RCPP
}
// pKolmogorov2x
double pKolmogorov2x(double statistic, int n);
RcppExport SEXP _DescToolsGraphics_pKolmogorov2x(SEXP statisticSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type statistic(statisticSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(pKolmogorov2x(statistic, n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DescToolsGraphics_pSmirnov2x", (DL_FUNC) &_DescToolsGraphics_pSmirnov2x, 3},
    {"_DescToolsGraphics_pKS2", (DL_FUNC) &_DescToolsGraphics_pKS2, 2},
    {"_DescToolsGraphics_pKolmogorov2x", (DL_FUNC) &_DescToolsGraphics_pKolmogorov2x, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_DescToolsGraphics(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
