# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pSmirnov2x <- function(statistic, nx, ny) {
    .Call(`_DescToolsGraphics_pSmirnov2x`, statistic, nx, ny)
}

pKS2 <- function(statistic, tol) {
    .Call(`_DescToolsGraphics_pKS2`, statistic, tol)
}

pKolmogorov2x <- function(statistic, n) {
    .Call(`_DescToolsGraphics_pKolmogorov2x`, statistic, n)
}

