# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

between_num <- function(x, from, to, left_closed = TRUE, right_closed = TRUE) {
    .Call(`_DescToolsViz_between_num`, x, from, to, left_closed, right_closed)
}

conv_DecToBin <- function(n) {
    .Call(`_DescToolsViz_conv_DecToBin`, n)
}

pSmirnov2x <- function(statistic, nx, ny) {
    .Call(`_DescToolsViz_pSmirnov2x`, statistic, nx, ny)
}

pKS2 <- function(statistic, tol) {
    .Call(`_DescToolsViz_pKS2`, statistic, tol)
}

pKolmogorov2x <- function(statistic, n) {
    .Call(`_DescToolsViz_pKolmogorov2x`, statistic, n)
}

roman2int_cpp <- function(x) {
    .Call(`_DescToolsViz_roman2int_cpp`, x)
}

